name: asimox
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

dependencies:
  domino: ^0.9.0
  web: ^1.1.0

dev_dependencies:
  lints: ^4.0.0
  html: ^0.15.4
  http: ^1.2.2
  test: ^1.24.0
