name: asimox
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

dependencies:
  domino: ^0.9.0
  web: ^1.1.0

dev_dependencies:
  lints: ^4.0.0
  html: ^0.15.4
  http: ^1.2.2
  test: ^1.24.0
  puppeteer: ^3.15.0
  build_runner: ^2.4.13
  build_web_compilers: ^4.0.11
  build_test: ^2.2.2
  webdev_proxy: ^0.1.12
  path: ^1.9.0
